name: city_vibes_app
description: "The City Vibes event management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0

  # --- OFFLINE STORAGE (NEW) ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  http: ^1.2.1
  
  # --- STRIPE UPDATED VERSIONS ---
  flutter_stripe: ^11.4.0
  flutter_stripe_web: ^6.1.0
  
  # --- FIREBASE ---
  cloud_functions: ^5.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0

  # UI Libraries
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # Latest intl
  intl: ^0.20.2
  
  font_awesome_flutter: ^10.7.0

  # State Management
  provider: ^6.1.2

  # Storage
  shared_preferences: ^2.2.3
  
  # Auth
  google_sign_in: ^6.2.1
  local_auth: ^2.2.0

  # Maps
  geolocator: ^13.0.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2

  # Sharing
  share_plus: ^10.0.0

  # QR Code Generation
  qr_flutter: ^4.1.0

  # Organizer & Utils
  image_picker: ^1.1.2
  uuid: ^4.4.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/